-- 0020_dispatch_effort.sql: the effort a dispatch's model ran at, recorded
-- intent exactly the way model already is (design.md's Enforcement).
--
-- The vocabulary is four words: low, medium, high -- the three efforts the
-- harness exposes -- and default, meaning no effort was set for this
-- dispatch. NOT NULL DEFAULT 'default' rather than a nullable column: an
-- absent effort is a known fact -- the dispatcher set none -- never an
-- unknown one, so it is stored as the word that says so rather than as
-- NULL, which would leave a reader unable to tell "recorded, no effort"
-- from "this row predates the column".
--
-- Unlike model, effort cannot be handshaken back from the dispatched role:
-- a model can report which model it is running as, but not the effort
-- level it was invoked at, so this column carries only what the dispatcher
-- itself set at `flow record dispatch begin` -- never a value read back
-- from the dispatch.
--
-- It is a NEW file rather than an edit to 0010_run_records.sql, for the
-- reason 0011_dispatch_agent_id.sql gives: migrations here are tracked by
-- filename with no checksum, so editing an applied one would leave an
-- existing database silently diverged from a freshly migrated one.
ALTER TABLE dispatches ADD COLUMN effort TEXT NOT NULL DEFAULT 'default';
